### ISSUE TITLE
General Desktop Lesson result is not well formated in search results

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-connect-plugin#18]
![image](https://user-images.githubusercontent.com/3607161/27286293-7c1692fa-54f7-11e7-8931-dc1d7b4ed00e.png)

**Comment by volaya** [comment]
I fixed this but is a dirty fix. The issue is rather strange and happens whenever the description is too short. That makes the title and description div move under the icon. It can be reproduced outside QGIS/Qt, so it's a CSS problem

My CSS skills are not enough to figure out why this is happening, so i have made a fix that ensures that descriptions are long enough, adding them with blank spaces if not.

The attached zipfile contains an example of a small webpage to demonstrate this issue. If anyone with more css skills can fix that, let me know and i will try to translate that to Connect, to have a more robust fix
[test.zip](https://github.com/boundlessgeo/qgis-connect-plugin/files/1090856/test.zip)

**Comment by SrNetoChan** [comment]
@KentPorter-Boundless this might be a task for you.

**Comment by SrNetoChan** [comment]
@volaya very strange issue. I would expect the oposite, that the title and description div is moved only if it's too big. But about CSS I only know the music band!

**Comment by KentPorter-Boundless** [comment]
I will take a look at this with Alex B. later today. Probably an easy fix.

**Comment by volaya** [comment]
Yes, exactly, I would also expect the opposite...but CSS is always a mystery :-P
